/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.product.usersvc;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

public class ApplicationTest {
    @Test public void testSomeLibraryMethod() {
        Application classUnderTest = new Application();
        assertTrue(classUnderTest != null, "someLibraryMethod should return 'true'");
    }
}
